- name: Deploy to EC2
  hosts: localhost
  connection: local

  tasks:
    - name: Launch EC2 instance
      ec2:
        instance_type: t2.micro
        image: ami-013f17f36f8b1fefb
        region: us-east-1
        key_name: devops-slavik
        vpc_subnet_id: subnet-c1b5b28c
        assign_public_ip: yes
        wait: yes
        count: 1
        group: eshop
        aws_access_key: "{{access_key}}"
        aws_secret_key: "{{secret_key}}"
        security_token: "{{security_token}}"

    - name: Add instance host to group
      add_host: hostname={{ item.public_dns_name }} groupname=launched
      with_items: '{{ec2.instances}}'

    - name: Wait for SSH conenection
      wait_for: host={{ item.public_dns_name }} port=22 delay=30 timeout=300 state=started
      with_items: '{{ec2.instances}}'

- name: Configure EC
  hosts: launched
  connection: ssh

  tasks:
    - name: Install docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
      become: yes
    - service:
        name: docker
        state: started
        enabled: yes
      become: yes
    - name: Get project files from github
      git:
        repo: 'https://github.com/NightingaleV/4IT572_circleci'
        dest: ./app
    - name: Build docker
      shell: cd app && docker build -t myeshop:latest .
      become: yes
    - name: Run Docker with Eshop
      shell: docker run -p 80:3000 myeshop
      async: 45
      poll: 10
      become: yes
    - wait_for:
        port: 80
